os: osx
osx_image: xcode10
language: swift
script: xcodebuild clean build -workspace "crafterCart.xcworkspace" -scheme crafterCart -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 8"
